[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools',
]

[project]
name = "nebari_helm_stage"
version = "0.0.1"
dependencies = [
    "nebari"
]

[project.entry-points.nebari]
nebari-helm-stage = "nebari_helm_stage"